# Generated by Django 5.1.1 on 2024-09-12 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='tittle',
            new_name='title',
        ),
    ]
