# Generated by Django 5.1.1 on 2024-09-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userprofile_cpf_userprofile_nome_completo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nome_completo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telefone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cpf',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
