# Generated by Django 5.1.1 on 2024-09-17 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_remove_userprofile_nome_completo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cpf',
        ),
    ]
